# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f696577a77095eb3fb9d2c892fe90dcb2e662d4f1afc97dc6488bda17ce6e0f22a0d35f0f20c2ab0f70d7497d282a1d7c9fdf3d0d4d94ceffb229cfb4268c6fb

test:
  secret_key_base: 83ba8a2951f9a48188a6610e086517e2bd5154d2b8fb63ef757d41ab155144e74ee82833d68fceb564630cb459406973b209ccac6c7a336ede8e637cd702a32a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
